server.port: 8081

spring:
  application.name: user-service
  ai:
    mcp:
      server:
        protocol: STATELESS
        name: stateless-mcp-server
        version: 1.0.0
        type: ASYNC
        instructions: "This stateless server is optimized for cloud deployments"
        streamable-http:
          mcp-endpoint: /api/mcp
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "user-service"
    description: "User MCP service for processing user & their financial transactions"
    version: "1.0"